[workspace]
members = [
    "amm_pool",
    "atomic_swap",
    "launch",
    "multi_phase_dao",
    "multisig",
    "nft",
    "registry",
    "timelock",
    "token",
    "vesting",
    "language",
    "package_graph",
    "scenario_basics",
]
